const sessions=[
{n:1,title:'Landscape Sistem dan Tata Kelola',mission:'Pahami perusahaan, aktor, tujuan, risiko, dan governance sebelum memilih kontrol.',metrics:[['8','Aktor kritis'],['6','Sistem utama'],['4','Risiko prioritas']],modules:['System landscape','Actor directory','Risk register'],records:[['SYS-01','Marketplace','API → ERP','Active','warn'],['SYS-02','Cloud ERP','Finance & operations','Active','ok'],['SYS-03','Payroll SaaS','HR & payroll','Active','warn']],evidence:['Struktur organisasi','Peta aplikasi','Risk appetite memo'],decision:['Lanjutkan desain','Minta klarifikasi','Eskalasi governance']},
{n:2,title:'Data, Dokumen, dan Lineage',mission:'Telusuri data dari source sampai output dan temukan titik kehilangan, duplikasi, atau perubahan.',metrics:[['2.4%','Reject rate'],['17','Unowned exceptions'],['3','Broken mappings']],modules:['Source documents','Interface queue','Data lineage'],records:[['ORD-1041','Marketplace order','Rejected','No owner','alert'],['ORD-1042','POS order','Posted','Complete','ok'],['MAP-07','Customer type','Old mapping','Used','warn']],evidence:['Source-to-target totals','Rejected queue','Mapping table'],decision:['Release data','Hold processing','Correct and reprocess']},
{n:3,title:'ERP Selection dan Implementasi',mission:'Nilai fit-gap, konfigurasi, migrasi, dan cutover readiness.',metrics:[['68%','Fit without change'],['12','Critical gaps'],['5','Cutover blockers']],modules:['Fit-gap register','Vendor scorecard','Cutover dashboard'],records:[['GAP-03','Pricing approval','Customisation','High','warn'],['MIG-08','Vendor bank data','Failed validation','Critical','alert'],['TST-11','Order-to-cash','Passed','Ready','ok']],evidence:['Fit-gap register','Migration results','Cutover checklist'],decision:['Go','Conditional go','No-go']},
{n:4,title:'Pengendalian Internal dan Framework',mission:'Hubungkan objective, risk, control, owner, evidence, dan deficiency.',metrics:[['14','Key controls'],['5','Design gaps'],['3','Monitoring gaps']],modules:['Control library','COSO map','Deficiency log'],records:[['CTRL-04','Vendor bank callback','Not designed','High','alert'],['CTRL-09','Access review','Late','Medium','warn'],['CTRL-12','Bank reconciliation','Operating','Low','ok']],evidence:['Risk-control matrix','Control descriptions','Monitoring report'],decision:['Control adequate','Revise design','Escalate deficiency']},
{n:5,title:'Audit SI dan CAATs',mission:'Pilih prosedur, validasi populasi, uji bukti, dan susun temuan.',metrics:[['100%','Rows analysed'],['7','Population gaps'],['11','Exceptions']],modules:['Audit program','Population validator','Finding builder'],records:[['POP-01','Privileged accounts','Vendor IDs excluded','Incomplete','alert'],['TEST-03','Price change','No UAT evidence','Exception','warn'],['TEST-08','Backup restore','Passed','Reliable','ok']],evidence:['Population extract','Audit log','Reperformance result'],decision:['Control effective','Control ineffective','Insufficient evidence']},
{n:6,title:'Revenue-to-Cash dan Procure-to-Pay',mission:'Ikuti transaksi, master data, matching, payment, exception, dan reconciliation.',metrics:[['9','Duplicate vendors'],['6','Credit overrides'],['780m','Unreconciled']],modules:['Sales orders','Procurement','Payments'],records:[['SO-5502','Credit override','No approval','Hold','alert'],['VEN-018','Bank changed','No callback','Hold','alert'],['INV-774','Three-way match','Passed','Release','ok']],evidence:['Sales order log','Vendor change report','Three-way match'],decision:['Release','Hold','Reverse / investigate']},
{n:7,title:'Produksi dan Cost Integrity',mission:'Telusuri BOM, MRP, material, MES, WIP, scrap, dan costing.',metrics:[['450kg','Material gap'],['4h','MES outage'],['1.24bn','WIP difference']],modules:['BOM & routing','Production orders','Cost ledger'],records:[['BOM-22','Component ratio','Changed unapproved','Critical','alert'],['MES-14','Machine log','4-hour gap','Incomplete','warn'],['WIP-09','Physical vs GL','Difference','Hold','alert']],evidence:['BOM version','MES log','WIP reconciliation'],decision:['Release margin','Adjust and hold','Escalate']},
{n:8,title:'HR dan Payroll Integrity',mission:'Telusuri employee master, attendance, calculation, payment file, GL, dan liabilities.',metrics:[['2','Terminated paid'],['1','File edited'],['780m','Difference']],modules:['Employee master','Payroll run','Bank file'],records:[['EMP-077','Terminated','Still active','Paid','alert'],['PAY-2407','Overtime','Approved late','Review','warn'],['BANK-88','Payment file','Edited after approval','Block','alert']],evidence:['Termination report','Payroll register','Bank response'],decision:['Release payroll','Hold payroll','Reverse / escalate']},
{n:9,title:'GL, Close, dan Pelaporan',mission:'Uji interface, journal, reconciliation, close, XBRL, dan narrative publication.',metrics:[['2.1bn','Interface gap'],['3.4bn','Unsupported journal'],['6','XBRL errors']],modules:['General ledger','Close cockpit','Digital reporting'],records:[['JRN-901','Manual journal','No support','Block','alert'],['REC-32','Revenue to GL','2.1bn gap','Block','alert'],['XBRL-7','Context/scale','Validation failed','Hold','warn']],evidence:['Close checklist','Journal support','XBRL validation'],decision:['Release','Hold','Qualify / correct']},
{n:10,title:'ICoFR Assessment',mission:'Lakukan scoping, walkthrough, testing, deficiency evaluation, aggregation, dan conclusion.',metrics:[['18','Key controls'],['6','Deficiencies'],['1','Potential MW']],modules:['Scoping','Testing','Deficiency evaluation'],records:[['REV-04','Revenue review','Threshold too high','Design gap','alert'],['ACC-02','Access review','Incomplete population','OE gap','warn'],['REM-03','XBRL remediation','Repeated error','Unproven','warn']],evidence:['Scoping memo','Test sheets','Deficiency summary'],decision:['Effective','Ineffective','Insufficient basis']},
{n:11,title:'Kasus Integratif I',mission:'Hubungkan data, ERP, process, controls, evidence, remediation, dan go/no-go decision.',metrics:[['34','Potential duplicates'],['2.6bn','Sales-GL gap'],['17','Aged issues']],modules:['Integrated dashboard','Evidence room','Steering decision'],records:[['VEN-34','Duplicate vendors','9 shared bank','Block','alert'],['IF-21','Rejected orders','Missing from queue','Block','alert'],['CHG-11','Pricing config','No UAT/rollback','Block','alert']],evidence:['Process map','Role matrix','Interface totals'],decision:['Go','Conditional go','No-go']},
{n:12,title:'Kasus Integratif II',mission:'Hubungkan payroll, close, reporting, deficiency aggregation, communication, dan ICoFR.',metrics:[['780m','Payroll gap'],['1.9bn','Unsupported journal'],['430m','Old suspense']],modules:['Payroll-to-report','Publication gates','ICoFR conclusion'],records:[['EMP-TERM','2 terminated staff','Still paid','Block','alert'],['JRN-19','Manual journal','Unsupported','Block','alert'],['AI-NAR','Narrative','Pre-close source','Hold','warn']],evidence:['Payroll reconciliation','Journal listing','Deficiency summary'],decision:['Release outputs','Hold selected outputs','ICoFR ineffective']},
{n:13,title:'Technology Readiness',mission:'Nilai cloud, cyber, AI, RPA, analytics, biometric, privacy, dan 30/60/90 remediation.',metrics:[['6','Critical gaps'],['4','Unowned controls'],['0','Recovery tests']],modules:['Cloud & SOC','Automation & AI','Readiness roadmap'],records:[['CUEC-04','Cloud user control','No owner','0–30','alert'],['BOT-02','RPA account','Shared credential','0–30','alert'],['BIO-03','Biometric data','No deletion rule','31–60','warn']],evidence:['SOC report','Bot register','Privacy assessment'],decision:['Ready','Conditionally ready','Not ready']},
{n:14,title:'Mock Certification',mission:'Selesaikan kasus terintegrasi dengan I-P-A-R-E-C dan buat keputusan profesional.',metrics:[['5','Priority issues'],['900','Max words'],['80%','Ready threshold']],modules:['Mock case','Answer workspace','Readiness review'],records:[['CASE-1','Vendor/access','Material risk','Priority','alert'],['CASE-2','Payroll/close','Publication blocker','Priority','alert'],['CASE-3','Remediation','One-week operation','ICoFR risk','warn']],evidence:['Integrated evidence pack','Marking guide','Peer review form'],decision:['Ready','Conditionally ready','Not ready']}
];
const state=JSON.parse(localStorage.getItem('sipi-sim-state')||'{}');let current=Number(state.current||1),view='dashboard',erpTab=0;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function save(){state.current=current;localStorage.setItem('sipi-sim-state',JSON.stringify(state))}
function session(){return sessions.find(x=>x.n===current)}
function init(){const sel=$('#sessionSelect');sessions.forEach(s=>sel.insertAdjacentHTML('beforeend',`<option value="${s.n}">Sesi ${s.n} — ${s.title}</option>`));sel.value=current;sel.onchange=e=>{current=Number(e.target.value);save();render()};$$('.nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#reset').onclick=()=>{if(confirm('Hapus seluruh catatan dan progres?')){localStorage.removeItem('sipi-sim-state');location.reload()}};render()}
function show(v){view=v;$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$$('.view').forEach(x=>x.classList.remove('active'));$('#'+v+'View').classList.add('active');renderView()}
function render(){const s=session();$('#caseTitle').textContent=`Sesi ${s.n} — ${s.title}`;renderView();updateProgress()}
function renderView(){const s=session();if(view==='dashboard')renderDashboard(s);if(view==='erp')renderERP(s);if(view==='evidence')renderEvidence(s);if(view==='investigation')renderInvestigation(s);if(view==='decision')renderDecision(s)}
function renderDashboard(s){$('#dashboardView').innerHTML=`<div class="hero"><div><small>PT NUSANIAGA • SIMULATION BRIEF</small><h3>${s.title}</h3><p>${s.mission}</p></div><div class="mission"><b>Misi Anda</b><p>Buka modul simulasi, periksa bukti, catat anomali, lalu ambil keputusan yang dapat dipertanggungjawabkan.</p></div></div><div class="grid three">${s.metrics.map((m,i)=>`<div class="card"><h3>${m[1]}</h3><div class="metric ${i===0?'red':i===1?'gold':'green'}">${m[0]}</div><div class="sub">Indikator awal—belum merupakan conclusion.</div></div>`).join('')}</div><div class="grid two"><div class="card"><h3>Alur investigasi</h3><p class="sub">1. Buka ERP mock-up → 2. drill-down record → 3. tinjau evidence → 4. catat clue → 5. pilih keputusan.</p></div><div class="card"><h3>Prinsip</h3><p class="sub">Aplikasi tidak langsung memberi jawaban benar. Anda harus menghubungkan fakta, risiko, kontrol, evidence, dan residual uncertainty.</p></div></div>`}
function renderERP(s){$('#erpView').innerHTML=`<div class="section-head"><div><h3>ERP Mock-up</h3><p>Lingkungan transaksi dan kontrol simulasi.</p></div><div class="toolbar"><button class="btn secondary" onclick="renderERP(session())">Refresh</button></div></div><div class="erp-shell"><div class="erp-menu">${s.modules.map((m,i)=>`<button class="${i===erpTab?'active':''}" onclick="erpTab=${i};renderERP(session())">${m}</button>`).join('')}</div><div class="erp-panel"><h3>${s.modules[erpTab]}</h3><p class="sub">Klik nomor record untuk melihat detail dan clue.</p><div class="table-wrap"><table><thead><tr><th>Record</th><th>Object</th><th>Condition</th><th>Status</th><th>Review</th></tr></thead><tbody>${s.records.map((r,i)=>`<tr class="${r[4]==='alert'?'row-alert':r[4]==='warn'?'row-warn':''}"><td><button class="record-btn" onclick="openRecord(${i})">${r[0]}</button></td><td>${r[1]}</td><td>${r[2]}</td><td><span class="status ${r[4]}">${r[3]}</span></td><td>${state[`rec-${current}-${i}`]?'Reviewed':'Open'}</td></tr>`).join('')}</tbody></table></div></div></div>`}
function openRecord(i){const r=session().records[i];$('#modalTitle').textContent=`${r[0]} — ${r[1]}`;$('#modalBody').innerHTML=`<div class="document"><b>Condition</b><p>${r[2]}</p><b>Current status</b><p>${r[3]}</p><div class="alert-box"><b>Investigation prompt</b><br>What objective or assertion is affected? What control should exist? What evidence is still missing?</div></div>`;$('#modal').classList.add('open');state[`rec-${current}-${i}`]=true;save();updateProgress()}
function renderEvidence(s){$('#evidenceView').innerHTML=`<div class="section-head"><div><h3>Evidence Room</h3><p>Dokumen, report, log, dan artefak simulasi.</p></div></div><div class="evidence-grid">${s.evidence.map((e,i)=>`<div class="evidence ${state[`ev-${current}-${i}`]?'reviewed':''}" onclick="openEvidence(${i})"><span class="type">Evidence ${String(i+1).padStart(2,'0')}</span><h4>${e}</h4><p>Open to inspect scope, period, exceptions, reliability, and limitations.</p></div>`).join('')}</div>`}
function openEvidence(i){const e=session().evidence[i];$('#modalTitle').textContent=e;$('#modalBody').innerHTML=`<div class="document"><h3>PT NusaNiaga — ${e}</h3><p><b>Period:</b> Current simulation period</p><p><b>Prepared by:</b> Process owner</p><p><b>Review status:</b> Requires student evaluation</p><table><tr><th>Test</th><th>Result</th></tr><tr><td>Population completeness</td><td>${i===1?'Exception noted':'To be assessed'}</td></tr><tr><td>Approval / review</td><td>${i===2?'Incomplete':'Available with limitation'}</td></tr></table><div class="hint"><b>Do not accept at face value.</b> Assess relevance, reliability, source, period, logic, and missing evidence.</div></div>`;$('#modal').classList.add('open');state[`ev-${current}-${i}`]=true;save();renderEvidence(session());updateProgress()}
function renderInvestigation(s){const key=`notes-${current}`;$('#investigationView').innerHTML=`<div class="section-head"><div><h3>Investigation Notebook</h3><p>Susun clue sebelum mengambil keputusan.</p></div></div><div class="investigation"><div class="clues">${s.records.map((r,i)=>`<div class="clue"><strong>${r[0]} — ${r[1]}</strong><p class="sub">${r[2]} • ${r[3]}</p><label><input type="checkbox" ${state[`clue-${current}-${i}`]?'checked':''} onchange="state['clue-${current}-${i}']=this.checked;save();updateProgress()"> Masukkan sebagai clue material</label></div>`).join('')}</div><div class="card notebook"><h3>Catatan profesional</h3><textarea id="notes" placeholder="Issue → risk/assertion → expected control → evidence/limitation → action → closure">${state[key]||''}</textarea><button class="btn" onclick="state['${key}']=$('#notes').value;save();updateProgress()">Simpan catatan</button></div></div>`}
function renderDecision(s){const key=`decision-${current}`,why=`why-${current}`;$('#decisionView').innerHTML=`<div class="section-head"><div><h3>Decision Gate</h3><p>Pilih keputusan dan pertahankan dengan evidence.</p></div></div><div class="decision-grid">${s.decision.map(d=>`<button class="decision ${state[key]===d?'selected':''}" onclick="state['${key}']='${d}';save();renderDecision(session());updateProgress()"><strong>${d}</strong><span class="sub">Select only after reviewing records and evidence.</span></button>`).join('')}</div><div class="card decision-form"><h3>Basis keputusan</h3><textarea id="why" placeholder="Relevant facts, principle, analysis, recommendation, evidence, residual uncertainty, conclusion">${state[why]||''}</textarea><button class="btn" onclick="state['${why}']=$('#why').value;save();updateProgress()">Simpan keputusan</button></div>`}
function updateProgress(){const s=session();let total=s.records.length+s.evidence.length+3,done=0;s.records.forEach((_,i)=>done+=state[`rec-${current}-${i}`]?1:0);s.evidence.forEach((_,i)=>done+=state[`ev-${current}-${i}`]?1:0);done+=state[`notes-${current}`]?1:0;done+=state[`decision-${current}`]?1:0;done+=state[`why-${current}`]?1:0;const p=Math.round(done/total*100);$('#progressBar').style.width=p+'%';$('#progressText').textContent=p+'%'}
window.openRecord=openRecord;window.openEvidence=openEvidence;window.renderERP=renderERP;window.session=session;window.state=state;window.save=save;window.updateProgress=updateProgress;$('#modalClose').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('open')};init();