const sessions=[
{n:1,title:'Landscape Sistem dan Tata Kelola',mission:'Pahami perusahaan, aktor, tujuan, risiko, dan governance sebelum memilih kontrol.',metrics:[['8','Aktor kritis'],['6','Sistem utama'],['4','Risiko prioritas']],modules:['System landscape','Actor directory','Risk register'],records:[['SYS-01','Marketplace','API → ERP','Active','warn'],['SYS-02','Cloud ERP','Finance & operations','Active','ok'],['SYS-03','Payroll SaaS','HR & payroll','Active','warn']],evidence:['Struktur organisasi','Peta aplikasi','Risk appetite memo'],decision:['Adequate','Conditionally adequate','Not adequate']},
{n:2,title:'Data, Dokumen, dan Lineage',mission:'Telusuri data dari source sampai output dan temukan titik kehilangan, duplikasi, atau perubahan.',metrics:[['2.4%','Reject rate'],['17','Unowned exceptions'],['3','Broken mappings']],modules:['Source documents','Interface queue','Data lineage'],records:[['ORD-1041','Marketplace order','Rejected','No owner','alert'],['ORD-1042','POS order','Posted','Complete','ok'],['MAP-07','Customer type','Old mapping','Used','warn']],evidence:['Source-to-target totals','Rejected queue','Mapping table'],decision:['Release data','Hold processing','Correct and reprocess']},
{n:3,title:'ERP Selection dan Implementasi',mission:'Nilai fit-gap, konfigurasi, migrasi, dan cutover readiness.',metrics:[['68%','Fit without change'],['12','Critical gaps'],['5','Cutover blockers']],modules:['Fit-gap register','Vendor scorecard','Cutover dashboard'],records:[['GAP-03','Pricing approval','Customisation','High','warn'],['MIG-08','Vendor bank data','Failed validation','Critical','alert'],['TST-11','Order-to-cash','Passed','Ready','ok']],evidence:['Fit-gap register','Migration results','Cutover checklist'],decision:['Go','Conditional go','No-go']},
{n:4,title:'Pengendalian Internal dan Framework',mission:'Hubungkan objective, risk, control, owner, evidence, dan deficiency.',metrics:[['14','Key controls'],['5','Design gaps'],['3','Monitoring gaps']],modules:['Control library','COSO map','Deficiency log'],records:[['CTRL-04','Vendor bank callback','Not designed','High','alert'],['CTRL-09','Access review','Late','Medium','warn'],['CTRL-12','Bank reconciliation','Operating','Low','ok']],evidence:['Risk-control matrix','Control descriptions','Monitoring report'],decision:['Control adequate','Revise design','Escalate deficiency']},
{n:5,title:'Audit SI dan CAATs',mission:'Pilih prosedur, validasi populasi, uji bukti, dan susun temuan.',metrics:[['100%','Rows analysed'],['7','Population gaps'],['11','Exceptions']],modules:['Audit program','Population validator','Finding builder'],records:[['POP-01','Privileged accounts','Vendor IDs excluded','Incomplete','alert'],['TEST-03','Price change','No UAT evidence','Exception','warn'],['TEST-08','Backup restore','Passed','Reliable','ok']],evidence:['Population extract','Audit log','Reperformance result'],decision:['Control effective','Control ineffective','Insufficient evidence']},
{n:6,title:'Revenue-to-Cash dan Procure-to-Pay',mission:'Ikuti transaksi, master data, matching, payment, exception, dan reconciliation.',metrics:[['9','Duplicate vendors'],['6','Credit overrides'],['780m','Unreconciled']],modules:['Sales orders','Procurement','Payments'],records:[['SO-5502','Credit override','No approval','Hold','alert'],['VEN-018','Bank changed','No callback','Hold','alert'],['INV-774','Three-way match','Passed','Release','ok']],evidence:['Sales order log','Vendor change report','Three-way match'],decision:['Release','Hold','Reverse / investigate']},
{n:7,title:'Produksi dan Cost Integrity',mission:'Telusuri BOM, MRP, material, MES, WIP, scrap, dan costing.',metrics:[['450kg','Material gap'],['4h','MES outage'],['1.24bn','WIP difference']],modules:['BOM & routing','Production orders','Cost ledger'],records:[['BOM-22','Component ratio','Changed unapproved','Critical','alert'],['MES-14','Machine log','4-hour gap','Incomplete','warn'],['WIP-09','Physical vs GL','Difference','Hold','alert']],evidence:['BOM version','MES log','WIP reconciliation'],decision:['Release margin','Adjust and hold','Escalate']},
{n:8,title:'HR dan Payroll Integrity',mission:'Telusuri employee master, attendance, calculation, payment file, GL, dan liabilities.',metrics:[['2','Terminated paid'],['1','File edited'],['780m','Difference']],modules:['Employee master','Payroll run','Bank file'],records:[['EMP-077','Terminated','Still active','Paid','alert'],['PAY-2407','Overtime','Approved late','Review','warn'],['BANK-88','Payment file','Edited after approval','Block','alert']],evidence:['Termination report','Payroll register','Bank response'],decision:['Release payroll','Hold payroll','Reverse / escalate']},
{n:9,title:'GL, Close, dan Pelaporan',mission:'Uji interface, journal, reconciliation, close, XBRL, dan narrative publication.',metrics:[['2.1bn','Interface gap'],['3.4bn','Unsupported journal'],['6','XBRL errors']],modules:['General ledger','Close cockpit','Digital reporting'],records:[['JRN-901','Manual journal','No support','Block','alert'],['REC-32','Revenue to GL','2.1bn gap','Block','alert'],['XBRL-7','Context/scale','Validation failed','Hold','warn']],evidence:['Close checklist','Journal support','XBRL validation'],decision:['Release','Hold','Qualify / correct']},
{n:10,title:'ICoFR Assessment',mission:'Lakukan scoping, walkthrough, testing, deficiency evaluation, aggregation, dan conclusion.',metrics:[['18','Key controls'],['6','Deficiencies'],['1','Potential MW']],modules:['Scoping','Testing','Deficiency evaluation'],records:[['REV-04','Revenue review','Threshold too high','Design gap','alert'],['ACC-02','Access review','Incomplete population','OE gap','warn'],['REM-03','XBRL remediation','Repeated error','Unproven','warn']],evidence:['Scoping memo','Test sheets','Deficiency summary'],decision:['Effective','Ineffective','Insufficient basis']},
{n:11,title:'Kasus Integratif I — Data, ERP, Proses, Pengendalian, dan Audit',mission:'Integrasikan data, ERP, process, controls, audit evidence, blocking conditions, remediation, dan quality-gate decision.',metrics:[['34','Potential duplicate vendors'],['2.6bn','Sales–GL gap'],['4','Critical blockers']],modules:['Master data & access','Interfaces & change','Reporting & assurance'],moduleRecords:[
[['VEN-11-01','Vendor master','34 potential duplicates; 9 shared bank accounts','Block','alert'],['ACC-11-02','Buyer role','Create vendor + approve PO','Block','alert']],
[['IF-11-03','Order interface','Rejected orders missing from queue','Investigate','alert'],['CHG-11-04','Pricing configuration','Changed without UAT/rollback evidence','Block','alert']],
[['REC-11-05','Sales reconciliation','Subledger differs from GL Rp2,6 miliar','Block','alert'],['AUD-11-06','Analytics population','Source total not independently reconciled','Limited','warn']]],
records:[['VEN-11-01','Vendor master','34 potential duplicates; 9 shared bank accounts','Block','alert'],['ACC-11-02','Buyer role','Create vendor + approve PO','Block','alert'],['IF-11-03','Order interface','Rejected orders missing from queue','Investigate','alert'],['CHG-11-04','Pricing configuration','Changed without UAT/rollback evidence','Block','alert'],['REC-11-05','Sales reconciliation','Subledger differs from GL Rp2,6 miliar','Block','alert'],['AUD-11-06','Analytics population','Source total not independently reconciled','Limited','warn']],
evidence:[
{id:'EV-11-01',title:'Vendor duplicate analytics',type:'Master data report',status:'Corroborated',reliability:'High',period:'Month-end',prepared:'Data analytics team',detail:'34 potential duplicate vendors; 9 pairs share bank accounts. Matching uses tax ID, bank account, address, and fuzzy name.',limitation:'Potential duplicate is not automatically duplicate; disposition and source-master verification are required.'},
{id:'EV-11-02',title:'Role-access matrix',type:'Access control matrix',status:'Confirmed fact',reliability:'High',period:'Current roles',prepared:'IAM administrator',detail:'Buyer role can create vendor master and approve purchase orders. No documented mitigating review for the conflicting combination.',limitation:'Matrix shows assigned access, not proof of actual misuse.'},
{id:'EV-11-03',title:'Interface exception log',type:'System log',status:'Incomplete evidence',reliability:'Medium',period:'Current month',prepared:'Integration platform',detail:'Rejected orders exist, but several records are absent from the operational queue and have no owner or disposition.',limitation:'Source-to-target population completeness has not yet been independently reconciled.'},
{id:'EV-11-04',title:'ERP change ticket CHG-11',type:'Change record',status:'Confirmed fact',reliability:'High',period:'Current release',prepared:'ERP team',detail:'Pricing configuration was approved for deployment; UAT evidence and tested rollback plan are blank.',limitation:'Approval alone does not demonstrate testing effectiveness.'},
{id:'EV-11-05',title:'Sales-to-GL reconciliation',type:'Reconciliation',status:'Conflicting evidence',reliability:'High',period:'Month-end close',prepared:'Financial controller',detail:'Sales subledger exceeds GL by Rp2,6 miliar; eight interface items remain unresolved.',limitation:'Root cause and financial-statement impact remain open.'}],
decision:['Go operations','Conditional go','No-go operations','Release reporting','Hold reporting'],instructor:{expected:['Separate operational decision from reporting decision.','Treat unresolved sales-to-GL difference as a reporting blocker until reconciled.','Do not infer fraud from duplicate-vendor indicators without corroboration.'],rubric:'Process/data map 20%; risk-control-evidence 25%; blocking conditions 20%; recommendation/closure 25%; professional communication 10%.'}},
{n:12,title:'Kasus Integratif II — Payroll, Financial Close, Reporting, dan ICoFR',mission:'Integrasikan payroll-to-report, close, publication gates, deficiency aggregation, komunikasi, dan ICoFR conclusion.',metrics:[['780m','Payroll gap'],['1.9bn','Unsupported journal'],['430m','Old suspense']],modules:['Payroll integrity','Close & reporting','ICoFR evaluation'],moduleRecords:[
[['EMP-12-01','Termination master','2 terminated staff remain active','Block','alert'],['BANK-12-02','Payment file','Edited after approval','Block','alert']],
[['JRN-12-03','Manual journal','Rp1,9 miliar unsupported','Block','alert'],['SUS-12-04','Suspense account','Rp430 juta >90 days','Hold','warn'],['XBRL-12-05','Digital reporting','Repeated context/scale errors','Hold','warn']],
[['AI-12-06','AI narrative','Uses pre-close data snapshot','Hold','warn'],['DEF-12-07','Deficiency summary','No aggregation analysis documented','Incomplete','alert']]],
records:[['EMP-12-01','Termination master','2 terminated staff remain active','Block','alert'],['BANK-12-02','Payment file','Edited after approval','Block','alert'],['JRN-12-03','Manual journal','Rp1,9 miliar unsupported','Block','alert'],['SUS-12-04','Suspense account','Rp430 juta >90 days','Hold','warn'],['XBRL-12-05','Digital reporting','Repeated context/scale errors','Hold','warn'],['AI-12-06','AI narrative','Uses pre-close data snapshot','Hold','warn'],['DEF-12-07','Deficiency summary','No aggregation analysis documented','Incomplete','alert']],
evidence:[
{id:'EV-12-01',title:'Payroll roster–register–bank–GL reconciliation',type:'Reconciliation pack',status:'Corroborated',reliability:'High',period:'Current payroll',prepared:'Payroll controller',detail:'Two terminated employees remain in payroll and register-to-bank-to-GL differences total Rp780 juta.',limitation:'Correction status and recovery evidence are not yet available.'},
{id:'EV-12-02',title:'Bank-file audit trail',type:'System audit log',status:'Confirmed fact',reliability:'High',period:'Payment run',prepared:'Treasury system',detail:'Beneficiary file was edited after approval; post-approval editor had elevated rights.',limitation:'Log proves change activity, not intent or loss.'},
{id:'EV-12-03',title:'Manual journal support pack',type:'Journal package',status:'Incomplete evidence',reliability:'Medium',period:'Close D+2',prepared:'Controller',detail:'Rp1,9 miliar journal has approval but lacks calculation support and independent evidence.',limitation:'Approval is not a substitute for substantive support.'},
{id:'EV-12-04',title:'Suspense ageing',type:'Account analysis',status:'Confirmed fact',reliability:'High',period:'Month-end',prepared:'Close team',detail:'Rp430 juta remains unresolved for more than 90 days; ownership and root cause are incomplete.',limitation:'Materiality and classification impact require evaluation.'},
{id:'EV-12-05',title:'XBRL validation and AI narrative pack',type:'Digital reporting pack',status:'Conflicting evidence',reliability:'Medium',period:'Pre-publication',prepared:'Reporting team',detail:'XBRL context/scale errors recur after correction; AI narrative was generated from a pre-close snapshot.',limitation:'Final corrected taxonomy file and approved data snapshot are not available.'},
{id:'EV-12-06',title:'ICoFR deficiency aggregation sheet',type:'Assessment',status:'Incomplete evidence',reliability:'Medium',period:'Year-to-date',prepared:'Management assessment team',detail:'Issues are listed individually; common cause, aggregation, compensating controls, and audit-committee communication are not documented.',limitation:'Cannot support an effective conclusion without completed evaluation.'}],
decision:['Release statements','Hold statements','Release XBRL','Hold XBRL','Release AI narrative','Hold AI narrative','ICoFR effective','ICoFR ineffective','Insufficient basis'],instructor:{expected:['Publication decisions may differ by output.','Correction of an error does not itself prove control effectiveness.','Aggregate deficiencies before concluding on ICoFR.'],rubric:'Payroll/close mapping 20%; reconciliation/evidence 25%; deficiency aggregation 25%; publication/ICoFR consistency 20%; communication 10%.'}},
{n:13,title:'Professional Update — Cloud, Cybersecurity, Analytics, AI, RPA, dan Privasi',mission:'Nilai teknologi baru sebagai extension dari Bab 1–9: shared responsibility, third-party assurance, AI/RPA governance, privacy, monitoring, dan remediation.',metrics:[['6','Critical gaps'],['4','Unowned controls'],['0','Recovery tests']],modules:['Cloud & SOC','AI & automation','Privacy & roadmap'],moduleRecords:[
[['CUEC-13-01','Cloud user control','No assigned owner','0–30','alert'],['SOC-13-02','SOC exception','Backup-recovery exception unresolved','0–30','alert']],
[['BOT-13-03','RPA identity','Two bots share credential','0–30','alert'],['AI-13-04','AI reporting','Prompt/output not retained','31–60','warn']],
[['BIO-13-05','Biometric data','No deletion/retention rule','31–60','warn'],['ROAD-13-06','Remediation plan','Owners incomplete','Review','warn']]],
records:[['CUEC-13-01','Cloud user control','No assigned owner','0–30','alert'],['SOC-13-02','SOC exception','Backup-recovery exception unresolved','0–30','alert'],['BOT-13-03','RPA identity','Two bots share credential','0–30','alert'],['AI-13-04','AI reporting','Prompt/output not retained','31–60','warn'],['BIO-13-05','Biometric data','No deletion/retention rule','31–60','warn'],['ROAD-13-06','Remediation plan','Owners incomplete','Review','warn']],
evidence:[
{id:'EV-13-01',title:'Cloud shared-responsibility matrix',type:'Control matrix',status:'Incomplete evidence',reliability:'High',period:'Current service',prepared:'Cloud governance team',detail:'Provider/customer responsibilities are mapped, but several CUECs lack named owners and evidence sources.',limitation:'Matrix design does not prove customer controls operate.'},
{id:'EV-13-02',title:'SOC report excerpt',type:'Third-party assurance',status:'Corroborated',reliability:'High',period:'Service period',prepared:'Independent service auditor',detail:'Relevant backup/recovery exception identified; complementary user entity controls are listed.',limitation:'Scope, period, subservice organizations, and CUECs must be matched to NusaNiaga use.'},
{id:'EV-13-03',title:'RPA bot register and credential log',type:'Automation register',status:'Confirmed fact',reliability:'High',period:'Current bots',prepared:'Automation CoE',detail:'Two production bots share a credential; direct production script change occurred without independent approval.',limitation:'Register does not prove whether the credential was abused.'},
{id:'EV-13-04',title:'AI reporting evidence log',type:'AI governance log',status:'Incomplete evidence',reliability:'Medium',period:'Current reporting cycle',prepared:'Reporting owner',detail:'Approved data snapshot is referenced, but prompt/output versions and reviewer evidence are not retained consistently.',limitation:'Cannot reconstruct all generated narrative versions.'},
{id:'EV-13-05',title:'Biometric privacy assessment',type:'Privacy assessment',status:'Incomplete evidence',reliability:'Medium',period:'Current policy',prepared:'HR/privacy team',detail:'Purpose is stated; retention, deletion, access recertification, and fallback procedure are absent.',limitation:'Legal compliance is not automatically established by this pedagogical assessment.'}],
decision:['Ready','Conditionally ready','Not ready'],instructor:{expected:['Cloud responsibility is shared, not fully transferred.','SOC reports require scope/CUEC analysis.','AI/RPA evidence must support traceability and human accountability.'],rubric:'Risk/responsibility mapping 25%; control design 25%; 30/60/90 prioritisation 20%; evidence/ownership 20%; communication 10%.'}},
{n:14,title:'Capstone dan Mock Certification',mission:'Selesaikan kasus terintegrasi dengan I-P-A-R-E-C, cite evidence, prioritise blockers, dan buat keputusan profesional dalam batas waktu.',metrics:[['5','Priority issues'],['45m','Suggested timer'],['80%','Readiness benchmark']],modules:['Integrated case','Evidence challenge','Readiness review'],moduleRecords:[
[['CASE-14-01','Vendor/access','21 duplicates; 7 shared banks; buyer conflict','Priority','alert'],['CASE-14-02','ERP change','Pricing change without UAT/rollback','Priority','alert']],
[['CASE-14-03','Payroll/close','Terminated staff + Rp2,8bn reconciliation gap','Priority','alert'],['CASE-14-04','Digital reporting','Repeated XBRL error + pre-close AI narrative','Priority','alert']],
[['CASE-14-05','Remediation','Key controls operate only one week','ICoFR risk','warn'],['CASE-14-06','Management explanation','All issues corrected before meeting','Uncorroborated','warn']]],
records:[['CASE-14-01','Vendor/access','21 duplicates; 7 shared banks; buyer conflict','Priority','alert'],['CASE-14-02','ERP change','Pricing change without UAT/rollback','Priority','alert'],['CASE-14-03','Payroll/close','Terminated staff + Rp2,8bn reconciliation gap','Priority','alert'],['CASE-14-04','Digital reporting','Repeated XBRL error + pre-close AI narrative','Priority','alert'],['CASE-14-05','Remediation','Key controls operate only one week','ICoFR risk','warn'],['CASE-14-06','Management explanation','All issues corrected before meeting','Uncorroborated','warn']],
evidence:[
{id:'EV-14-01',title:'Final vendor analytics and role matrix',type:'Integrated master/access pack',status:'Corroborated',reliability:'High',period:'Final case period',prepared:'Assurance team',detail:'21 potential duplicates, 7 shared bank accounts, and buyer-role conflict remain in scope.',limitation:'Duplicate indicators require disposition; role conflict does not prove misuse.'},
{id:'EV-14-02',title:'Final ERP change report',type:'Change management pack',status:'Confirmed fact',reliability:'High',period:'Final release',prepared:'ERP PMO',detail:'Pricing configuration deployed with approval but without retained UAT evidence or tested rollback plan.',limitation:'Post-deployment absence of incident does not prove change control effectiveness.'},
{id:'EV-14-03',title:'Final payroll and close pack',type:'Financial reporting pack',status:'Corroborated',reliability:'High',period:'Final close',prepared:'Finance assurance',detail:'Terminated staff paid, bank file edited after approval, subledger–GL difference Rp2,8 miliar, and unsupported journal Rp2,2 miliar.',limitation:'Final correction and recovery evidence are incomplete.'},
{id:'EV-14-04',title:'Digital reporting validation',type:'XBRL/AI pack',status:'Conflicting evidence',reliability:'Medium',period:'Pre-publication',prepared:'Reporting team',detail:'XBRL error repeated after remediation; AI narrative references a pre-close snapshot.',limitation:'Corrected final files are not yet independently validated.'},
{id:'EV-14-05',title:'Remediation operating-evidence tracker',type:'ICoFR evidence',status:'Incomplete evidence',reliability:'High',period:'One week',prepared:'Control owners',detail:'Redesigned controls have operated for only one week with limited samples and no sustained-period evidence.',limitation:'Insufficient operating history may prevent an effective operating-effectiveness conclusion.'},
{id:'EV-14-06',title:'Management representation',type:'Management explanation',status:'Management representation',reliability:'Low',period:'Case meeting',prepared:'Management',detail:'Management states all issues were corrected before the meeting and requests release of all outputs.',limitation:'Representation is not independent corroboration and conflicts with incomplete closure evidence.'}],
decision:['Go operations','Conditional operations','No-go operations','Release statements','Hold statements','Release XBRL','Hold XBRL','Release narrative','Hold narrative','ICoFR effective','ICoFR ineffective','Insufficient basis'],timer:45,instructor:{expected:['Require evidence citations, not generic conclusions.','Management representation must be corroborated.','One week of operation may be insufficient to conclude sustained operating effectiveness.','Alternative defensible judgments are acceptable if assumptions and safeguards are explicit.'],rubric:'Issue/principle 25%; analysis 25%; evidence use 20%; recommendation/closure 15%; conclusion consistency 10%; professional communication 5%.'}}
];

const state=JSON.parse(localStorage.getItem('sipi-sim-state')||'{}');
let current=Number(state.current||1),view='dashboard',erpTab=0,role=state.role||'student',timerHandle=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function save(){state.current=current;state.role=role;localStorage.setItem('sipi-sim-state',JSON.stringify(state))}
function session(){return sessions.find(x=>x.n===current)}
function evidenceId(s,i){const e=s.evidence[i];return typeof e==='string'?`EV-${String(s.n).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`:e.id}
function evidenceObj(s,i){const e=s.evidence[i];if(typeof e==='object')return e;return{id:evidenceId(s,i),title:e,type:'Simulation artefact',status:'Requires evaluation',reliability:'Unrated',period:'Current simulation period',prepared:'Process owner',detail:'Inspect this artefact for relevance, scope, exceptions, approval, and traceability.',limitation:'This legacy evidence is intentionally concise; identify what additional evidence is needed.'}}
function activeRecords(s){return s.moduleRecords?s.moduleRecords[erpTab]||[]:s.records}
function init(){const sel=$('#sessionSelect');sessions.forEach(s=>sel.insertAdjacentHTML('beforeend',`<option value="${s.n}">Sesi ${s.n} — ${s.title}</option>`));sel.value=current;sel.onchange=e=>{current=Number(e.target.value);erpTab=0;stopTimer();save();render()};$$('.nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#studentMode').onclick=()=>setRole('student');$('#instructorMode').onclick=()=>setRole('instructor');$('#reset').onclick=()=>{if(confirm('Hapus seluruh catatan dan progres?')){localStorage.removeItem('sipi-sim-state');location.reload()}};$('#exportJson').onclick=exportJSON;$('#printReport').onclick=()=>window.print();setRole(role,false);render()}
function setRole(r,rerender=true){role=r;save();$('#studentMode').classList.toggle('active',r==='student');$('#instructorMode').classList.toggle('active',r==='instructor');$('#rolePill').textContent=r==='instructor'?'Instructor mode':'Student mode';$('#modeNote').textContent=r==='instructor'?'Instructor Mode menampilkan debrief guidance dan rubric guidance. Pada repo publik ini bukan security boundary.':'Student Mode menyembunyikan panduan debrief dan rubric guidance.';if(rerender)renderView()}
function show(v){view=v;$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$$('.view').forEach(x=>x.classList.remove('active'));$('#'+v+'View').classList.add('active');renderView()}
function render(){const s=session();$('#caseTitle').textContent=`Sesi ${s.n} — ${s.title}`;renderView();updateProgress();updateTimerUI()}
function renderView(){const s=session();if(view==='dashboard')renderDashboard(s);if(view==='erp')renderERP(s);if(view==='evidence')renderEvidence(s);if(view==='investigation')renderInvestigation(s);if(view==='decision')renderDecision(s)}
function instructorPanel(s){if(role!=='instructor'||!s.instructor)return'';return`<div class="card instructor-panel"><span class="eyebrow">Instructor only</span><h3>Debrief & rubric guidance</h3><ul>${s.instructor.expected.map(x=>`<li>${x}</li>`).join('')}</ul><p><b>Rubric:</b> ${s.instructor.rubric}</p></div>`}
function renderDashboard(s){const timer=s.timer?`<div class="card"><h3>Mock certification timer</h3><p class="sub">Suggested ${s.timer} minutes. Timer is optional and local to this browser.</p><button class="btn" onclick="startTimer(${s.timer})">Start ${s.timer}-minute timer</button> <button class="btn secondary" onclick="stopTimer()">Stop</button></div>`:'';$('#dashboardView').innerHTML=`<div class="hero"><div><small>PT NUSANIAGA • SIMULATION BRIEF</small><h3>${s.title}</h3><p>${s.mission}</p></div><div class="mission"><b>Misi Anda</b><p>Buka modul simulasi, periksa bukti, dokumentasikan keterbatasan, lalu ambil keputusan yang dapat dipertanggungjawabkan.</p></div></div><div class="grid three">${s.metrics.map((m,i)=>`<div class="card"><h3>${m[1]}</h3><div class="metric ${i===0?'red':i===1?'gold':'green'}">${m[0]}</div><div class="sub">Indikator awal—belum merupakan conclusion.</div></div>`).join('')}</div><div class="grid two"><div class="card"><h3>Alur investigasi</h3><p class="sub">1. ERP mock-up → 2. drill-down record → 3. evidence review → 4. clue & citation → 5. structured decision.</p></div><div class="card"><h3>Prinsip evidence</h3><p class="sub">Bedakan confirmed fact, incomplete evidence, conflicting evidence, management representation, dan corroborated evidence. Jangan menyamakan indikator dengan kesimpulan.</p></div>${timer}</div>${instructorPanel(s)}`}
function renderERP(s){const rs=activeRecords(s);$('#erpView').innerHTML=`<div class="section-head"><div><h3>ERP Mock-up</h3><p>Dataset berubah sesuai modul untuk Sesi 11–14.</p></div></div><div class="erp-shell"><div class="erp-menu">${s.modules.map((m,i)=>`<button class="${i===erpTab?'active':''}" onclick="erpTab=${i};renderERP(session())">${m}</button>`).join('')}</div><div class="erp-panel"><h3>${s.modules[erpTab]}</h3><p class="sub">Klik record untuk melihat condition dan investigation prompt.</p><div class="table-wrap"><table><thead><tr><th>Record</th><th>Object</th><th>Condition</th><th>Status</th><th>Review</th></tr></thead><tbody>${rs.map((r,i)=>{const globalIndex=s.records.findIndex(x=>x[0]===r[0]);return`<tr class="${r[4]==='alert'?'row-alert':r[4]==='warn'?'row-warn':''}"><td><button class="record-btn" onclick="openRecord(${globalIndex})">${r[0]}</button></td><td>${r[1]}</td><td>${r[2]}</td><td><span class="status ${r[4]}">${r[3]}</span></td><td>${state[`rec-${current}-${globalIndex}`]?'Reviewed':'Open'}</td></tr>`}).join('')}</tbody></table></div></div></div>`}
function openRecord(i){const r=session().records[i];$('#modalTitle').textContent=`${r[0]} — ${r[1]}`;$('#modalBody').innerHTML=`<div class="document"><b>Condition</b><p>${r[2]}</p><b>Current status</b><p>${r[3]}</p><div class="alert-box"><b>Investigation prompt</b><br>Objective/assertion apa yang terdampak? Kontrol apa yang seharusnya ada? Evidence apa yang mendukung atau masih hilang? Apakah record ini harus dicite pada keputusan?</div></div>`;$('#modal').classList.add('open');state[`rec-${current}-${i}`]=true;save();updateProgress()}
function renderEvidence(s){$('#evidenceView').innerHTML=`<div class="section-head"><div><h3>Evidence Room</h3><p>Nilai source, reliability, completeness, conflict, dan limitation.</p></div></div><div class="evidence-grid">${s.evidence.map((_,i)=>{const e=evidenceObj(s,i);return`<div class="evidence ${state[`ev-${current}-${i}`]?'reviewed':''}" onclick="openEvidence(${i})"><span class="type">${e.id} • ${e.type}</span><h4>${e.title}</h4><div class="evidence-tags"><span>${e.status}</span><span>Reliability: ${e.reliability}</span></div><p>${e.detail}</p></div>`}).join('')}</div>`}
function openEvidence(i){const e=evidenceObj(session(),i);$('#modalTitle').textContent=`${e.id} — ${e.title}`;$('#modalBody').innerHTML=`<div class="document"><h3>PT NusaNiaga — ${e.title}</h3><table><tr><th>Field</th><th>Value</th></tr><tr><td>Evidence ID</td><td>${e.id}</td></tr><tr><td>Type</td><td>${e.type}</td></tr><tr><td>Status</td><td>${e.status}</td></tr><tr><td>Reliability</td><td>${e.reliability}</td></tr><tr><td>Period</td><td>${e.period}</td></tr><tr><td>Prepared by</td><td>${e.prepared}</td></tr></table><h4>Observed content</h4><p>${e.detail}</p><div class="hint"><b>Limitation:</b> ${e.limitation}</div><div class="citation-box"><b>Citation token:</b> <code>${e.id}</code><br>Gunakan ID ini pada Investigation Notebook dan Decision Gate.</div></div>`;$('#modal').classList.add('open');state[`ev-${current}-${i}`]=true;save();renderEvidence(session());updateProgress()}
function citationOptions(s){return s.evidence.map((_,i)=>{const e=evidenceObj(s,i),key=`cite-${current}-${e.id}`;return`<label class="citation-option"><input type="checkbox" ${state[key]?'checked':''} onchange="state['${key}']=this.checked;save();updateProgress()"> <b>${e.id}</b> ${e.title}</label>`}).join('')}
function selectedCitations(s){return s.evidence.map((_,i)=>evidenceObj(s,i)).filter(e=>state[`cite-${current}-${e.id}`]).map(e=>e.id)}
function renderInvestigation(s){const key=`notes-${current}`;$('#investigationView').innerHTML=`<div class="section-head"><div><h3>Investigation Notebook</h3><p>Susun clue dan cite evidence sebelum mengambil keputusan.</p></div></div><div class="investigation"><div><div class="clues">${s.records.map((r,i)=>`<div class="clue"><strong>${r[0]} — ${r[1]}</strong><p class="sub">${r[2]} • ${r[3]}</p><label><input type="checkbox" ${state[`clue-${current}-${i}`]?'checked':''} onchange="state['clue-${current}-${i}']=this.checked;save();updateProgress()"> Material clue</label></div>`).join('')}</div><div class="card citation-selector"><h3>Evidence citations</h3>${citationOptions(s)}</div></div><div class="card notebook"><h3>I-P-A-R-E-C notes</h3><textarea id="notes" placeholder="Issue → Principle → Analysis → Recommendation → Evidence IDs → Conclusion">${state[key]||''}</textarea><button class="btn" onclick="state['${key}']=$('#notes').value;save();updateProgress()">Simpan catatan</button></div></div>`}
function renderDecision(s){const key=`decision-${current}`,why=`why-${current}`,cites=selectedCitations(s);const citationWarning=cites.length?`<div class="citation-summary"><b>Cited evidence:</b> ${cites.join(', ')}</div>`:`<div class="alert-box"><b>Belum ada evidence citation.</b> Pilih minimal satu evidence di Investigation Notebook sebelum menyimpan basis keputusan.</div>`;$('#decisionView').innerHTML=`<div class="section-head"><div><h3>Decision Gate</h3><p>Pilih keputusan dan pertahankan dengan traceable evidence.</p></div></div><div class="decision-grid">${s.decision.map(d=>`<button class="decision ${state[key]===d?'selected':''}" onclick="state['${key}']='${d.replaceAll("'","\\'")}';save();renderDecision(session());updateProgress()"><strong>${d}</strong><span class="sub">Select only after reviewing records and evidence.</span></button>`).join('')}</div><div class="card decision-form"><h3>Structured justification</h3>${citationWarning}<textarea id="why" placeholder="Issue | Principle | Analysis | Recommendation | Evidence IDs | Residual uncertainty | Conclusion">${state[why]||''}</textarea><button class="btn" onclick="saveDecisionBasis()">Simpan keputusan</button></div>${instructorPanel(s)}`}
function saveDecisionBasis(){const s=session(),c=selectedCitations(s);if(!c.length){alert('Pilih minimal satu evidence citation di Investigation Notebook terlebih dahulu.');return}const text=$('#why').value.trim();if(text.length<80){alert('Basis keputusan terlalu singkat. Jelaskan issue, principle, analysis, recommendation, evidence, dan residual uncertainty.');return}state[`why-${current}`]=text;save();updateProgress();alert('Basis keputusan tersimpan dengan evidence citation: '+c.join(', '))}
function updateProgress(){const s=session();let total=s.records.length+s.evidence.length+4,done=0;s.records.forEach((_,i)=>done+=state[`rec-${current}-${i}`]?1:0);s.evidence.forEach((_,i)=>done+=state[`ev-${current}-${i}`]?1:0);done+=state[`notes-${current}`]?1:0;done+=state[`decision-${current}`]?1:0;done+=state[`why-${current}`]?1:0;done+=selectedCitations(s).length?1:0;const p=Math.round(done/total*100);$('#progressBar').style.width=p+'%';$('#progressText').textContent=p+'%'}
function buildExport(){const s=session();return{app:'SIPI Integrated Case & Certification Lab',company:'PT NusaNiaga',session:s.n,title:s.title,role,exportedAt:new Date().toISOString(),reviewedRecords:s.records.filter((_,i)=>state[`rec-${current}-${i}`]).map(r=>r[0]),reviewedEvidence:s.evidence.map((_,i)=>evidenceObj(s,i)).filter((_,i)=>state[`ev-${current}-${i}`]).map(e=>({id:e.id,title:e.title,status:e.status,reliability:e.reliability})),materialClues:s.records.filter((_,i)=>state[`clue-${current}-${i}`]).map(r=>r[0]),citations:selectedCitations(s),notes:state[`notes-${current}`]||'',decision:state[`decision-${current}`]||'',justification:state[`why-${current}`]||'',progress:$('#progressText').textContent}}
function exportJSON(){const obj=buildExport(),blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`SIPI_Sesi_${current}_hasil.json`;a.click();URL.revokeObjectURL(a.href)}
function startTimer(minutes){stopTimer();state.timerEnd=Date.now()+minutes*60000;save();timerHandle=setInterval(updateTimerUI,1000);updateTimerUI()}
function stopTimer(){if(timerHandle)clearInterval(timerHandle);timerHandle=null;delete state.timerEnd;save();updateTimerUI()}
function updateTimerUI(){const el=$('#timerPill');if(!el)return;if(!state.timerEnd||current!==14){el.classList.add('hidden');return}const remain=Math.max(0,state.timerEnd-Date.now());el.classList.remove('hidden');const m=Math.floor(remain/60000),sec=Math.floor((remain%60000)/1000);el.textContent=`${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`;if(remain<=0){el.textContent='TIME';if(timerHandle)clearInterval(timerHandle);timerHandle=null}}
window.openRecord=openRecord;window.openEvidence=openEvidence;window.renderERP=renderERP;window.session=session;window.state=state;window.save=save;window.updateProgress=updateProgress;window.startTimer=startTimer;window.stopTimer=stopTimer;window.saveDecisionBasis=saveDecisionBasis;$('#modalClose').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('open')};init();