const PASSWORD_HASH="f095af2c8fdec7f0ec3bc9201d093a9c7b90ecf4c21cd356bcbee01fcc9c97c7";
const STORAGE_KEY="sipi_uts_reguler_workspace_v1";
const START_KEY="sipi_uts_reguler_started";
const UNLOCK_KEY="sipi_uts_reguler_unlocked";
const state={currentId:null,workspace:loadWorkspace()};
function loadWorkspace(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{"reviewed":[],"bookmarks":[],"notes":{},"events":[]}')}catch(e){return{reviewed:[],bookmarks:[],notes:{},events:[]}}}
function saveWorkspace(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.workspace));updateMetrics()}
function uniq(a){return[...new Set(a)]}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
async function sha256(text){const data=new TextEncoder().encode(text);const digest=await crypto.subtle.digest("SHA-256",data);return[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function logEvent(action,id){state.workspace.events.push({ts:new Date().toISOString(),action,id});saveWorkspace()}
const gate=document.getElementById("gate"),app=document.getElementById("app"),msg=document.getElementById("gate-msg"),modal=document.getElementById("modal");
document.getElementById("unlock").addEventListener("click",async()=>{if(await sha256(document.getElementById("pw").value)===PASSWORD_HASH){localStorage.setItem(UNLOCK_KEY,"1");if(!localStorage.getItem(START_KEY))localStorage.setItem(START_KEY,String(Date.now()));gate.classList.add("hidden");app.classList.remove("hidden");boot()}else msg.textContent="Password tidak cocok."});
document.getElementById("pw").addEventListener("keydown",e=>{if(e.key==="Enter")document.getElementById("unlock").click()});
function boot(){populateCategories();renderEvidence();updateMetrics();startTimer()}
function populateCategories(){const s=document.getElementById("category-filter");uniq(EVIDENCE_DATA.map(x=>x.category)).sort().forEach(c=>s.insertAdjacentHTML("beforeend",'<option value="'+esc(c)+'">'+esc(c)+'</option>'))}
function filtered(){const q=document.getElementById("search").value.trim().toLowerCase(),cat=document.getElementById("category-filter").value,rf=document.getElementById("review-filter").value;return EVIDENCE_DATA.filter(x=>{const blob=[x.id,x.category,x.title,x.type,x.source,x.summary,x.focus,...x.sections.flatMap(s=>[s.heading||"",s.text||"",...(s.headers||[]),...(s.rows||[]).flat()])].join(" ").toLowerCase();if(q&&!blob.includes(q))return false;if(cat!=="ALL"&&x.category!==cat)return false;if(rf==="UNREVIEWED"&&state.workspace.reviewed.includes(x.id))return false;if(rf==="BOOKMARKED"&&!state.workspace.bookmarks.includes(x.id))return false;if(rf==="NOTED"&&!(state.workspace.notes[x.id]||"").trim())return false;return true})}
function renderEvidence(){const grid=document.getElementById("evidence-grid");grid.innerHTML="";filtered().forEach(x=>{const rev=state.workspace.reviewed.includes(x.id),bm=state.workspace.bookmarks.includes(x.id);const a=document.createElement("article");a.className="evidence";a.innerHTML='<div class="evidence-top"><div><div class="id">'+esc(x.id)+' — '+esc(x.title)+'</div><div class="meta-line">'+esc(x.type)+' • '+esc(x.source)+'</div></div><button class="bookmark-mini '+(bm?'active':'')+'" data-id="'+x.id+'">'+(bm?'★':'☆')+'</button></div><p>'+esc(x.summary)+'</p><div class="focus-mini"><strong>Fokus:</strong> '+esc(x.focus)+'</div><div class="card-footer"><span class="tag">'+esc(x.category)+'</span><span class="review-state">'+(rev?'Sudah dibuka':'Belum dibuka')+'</span></div><button class="inspect" data-id="'+x.id+'">Buka bukti</button>';grid.appendChild(a)});grid.querySelectorAll(".inspect").forEach(b=>b.onclick=()=>openEvidence(b.dataset.id));grid.querySelectorAll(".bookmark-mini").forEach(b=>b.onclick=e=>{e.stopPropagation();toggleBookmark(b.dataset.id);renderEvidence()})}
function renderSection(s){let h='<section class="artifact-section"><h3>'+esc(s.heading)+'</h3>';if(s.text)h+='<p>'+esc(s.text)+'</p>';if(s.headers&&s.rows){h+='<div class="table-wrap"><table><thead><tr>'+s.headers.map(x=>'<th>'+esc(x)+'</th>').join("")+'</tr></thead><tbody>'+s.rows.map(r=>'<tr>'+r.map(v=>'<td>'+esc(v)+'</td>').join("")+'</tr>').join("")+'</tbody></table></div>'}return h+'</section>'}
function openEvidence(id){const x=EVIDENCE_DATA.find(e=>e.id===id);state.currentId=id;if(!state.workspace.reviewed.includes(id)){state.workspace.reviewed.push(id);logEvent("open",id)}document.getElementById("modal-eyebrow").textContent=x.category+" • "+x.id;document.getElementById("modal-title").textContent=x.title;document.getElementById("modal-summary").textContent=x.summary;document.getElementById("focus-box").innerHTML="<strong>Petunjuk fokus:</strong> "+esc(x.focus);document.getElementById("modal-meta").innerHTML=[["Jenis",x.type],["Sumber",x.source],["Tanggal",x.date],["Evidence ID",x.id]].map(([k,v])=>'<div><span>'+esc(k)+'</span><strong>'+esc(v)+'</strong></div>').join("");document.getElementById("modal-sections").innerHTML=x.sections.map(renderSection).join("");document.getElementById("note").value=state.workspace.notes[id]||"";updateBookmarkButton();modal.classList.remove("hidden");renderEvidence();updateMetrics()}
function closeModal(){modal.classList.add("hidden");state.currentId=null}
document.getElementById("close-modal").onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!modal.classList.contains("hidden"))closeModal()});
function toggleBookmark(id){const i=state.workspace.bookmarks.indexOf(id);if(i>=0)state.workspace.bookmarks.splice(i,1);else state.workspace.bookmarks.push(id);state.workspace.bookmarks=uniq(state.workspace.bookmarks);logEvent(i>=0?"bookmark-remove":"bookmark-add",id);updateBookmarkButton()}
function updateBookmarkButton(){if(!state.currentId)return;const b=document.getElementById("bookmark-btn"),active=state.workspace.bookmarks.includes(state.currentId);b.textContent=active?"★ Ditandai":"☆ Tandai";b.classList.toggle("active",active)}
document.getElementById("bookmark-btn").onclick=()=>state.currentId&&toggleBookmark(state.currentId);
document.getElementById("save-note").onclick=()=>{if(!state.currentId)return;state.workspace.notes[state.currentId]=document.getElementById("note").value.trim();logEvent("note-save",state.currentId);document.getElementById("save-state").textContent="Tersimpan "+new Date().toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit"});renderEvidence()};
function updateMetrics(){document.getElementById("metric-reviewed").textContent=state.workspace.reviewed.length;document.getElementById("metric-notes").textContent=Object.values(state.workspace.notes).filter(v=>(v||"").trim()).length;document.getElementById("metric-bookmarks").textContent=state.workspace.bookmarks.length}
["search","category-filter","review-filter"].forEach(id=>document.getElementById(id).addEventListener(id==="search"?"input":"change",renderEvidence));
document.getElementById("print-btn").onclick=()=>window.print();
document.getElementById("export-btn").onclick=()=>{const payload={case:"UTS SIPI Reguler Sesi 1-7",exportedAt:new Date().toISOString(),reviewed:state.workspace.reviewed,bookmarks:state.workspace.bookmarks,notes:state.workspace.notes,activity:state.workspace.events};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="UTS_SIPI_Reguler_catatan.json";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);logEvent("export","ALL")};
function startTimer(){const started=Number(localStorage.getItem(START_KEY)||Date.now()),end=started+24*60*60*1000,el=document.getElementById("timer");const tick=()=>{const left=Math.max(0,end-Date.now()),h=Math.floor(left/3600000),m=Math.floor((left%3600000)/60000),s=Math.floor((left%60000)/1000);el.textContent=[h,m,s].map(v=>String(v).padStart(2,"0")).join(":")};tick();setInterval(tick,1000)}
if(localStorage.getItem(UNLOCK_KEY)==="1"){gate.classList.add("hidden");app.classList.remove("hidden");boot()}