const STORAGE_KEY='kasus-citibank-investigasi-v1';
const state=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');
state.view=state.view||'briefing';state.reviewed=state.reviewed||{};state.notes=state.notes||'';state.clues=state.clues||{};state.decision=state.decision||'';state.rationale=state.rationale||'';state.stage=state.stage||1;
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const titles={briefing:'Briefing Kasus',transaksi:'Eksplorasi Transaksi',jaringan:'Jaringan Rekening',formulir:'Form Transfer',bukti:'Wawancara & Bukti',notebook:'Notebook Investigasi',kesimpulan:'Kesimpulan Profesional'};
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function src(id){return KASUS.sumber.find(x=>x.id===id)}
function prov(p){return `<span class="prov ${p==='primer'?'primary':p==='sekunder'?'secondary':'recon'}">${p==='primer'?'BUKTI PRIMER':p==='sekunder'?'BUKTI SEKUNDER':'REKONSTRUKSI'}</span>`}
function formatAmount(v,c){if(v===null)return 'Tidak terekspos';return new Intl.NumberFormat('id-ID',{maximumFractionDigits:2}).format(v)+(c?` ${c}`:'')}
function sourceBox(id){if(!id)return `<div class="source-box">Artefak ini merupakan rekonstruksi pembelajaran dan bukan dokumen asli Citibank.</div>`;const s=src(id);return `<div class="source-box"><b>Sumber ${s.id} — ${s.lembaga}</b><br>${s.judul}<br><a href="${s.url}" target="_blank" rel="noopener">Buka sumber publik</a></div>`}
function init(){
  $$('#mainNav button').forEach(b=>b.onclick=()=>show(b.dataset.view));
  $('#resetBtn').onclick=()=>{if(confirm('Hapus seluruh progres investigasi pada browser ini?')){localStorage.removeItem(STORAGE_KEY);location.reload()}};
  $('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
  show(state.view,false);updateProgress();
}
function show(view,persist=true){state.view=view;if(persist)save();$$('.view').forEach(v=>v.classList.remove('active'));$('#'+view+'View').classList.add('active');$$('#mainNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#viewTitle').textContent=titles[view];render(view);updateProgress()}
function render(view){({briefing:renderBriefing,transaksi:renderTransaksi,jaringan:renderJaringan,formulir:renderFormulir,bukti:renderBukti,notebook:renderNotebook,kesimpulan:renderKesimpulan}[view])()}
function renderBriefing(){
  $('#briefingView').innerHTML=`<div class="hero"><div><span class="eyebrow">KASUS HISTORIS • INDONESIA</span><h3>${KASUS.metadata.judul}</h3><p>${KASUS.metadata.subjudul}</p><p>${KASUS.metadata.tujuan}</p></div><div class="mission"><b>Peran Anda</b><p>Anda adalah anggota tim review forensik independen. Tugas Anda bukan menebak siapa yang bersalah, tetapi menilai bagaimana transaksi diproses, diotorisasi, diverifikasi, dicatat, dan dimonitor.</p></div></div>
  <div class="grid three"><div class="card"><h3>Fokus sistem</h3><div class="metric gold">Otorisasi</div><p class="sub">Apakah instruksi transaksi benar-benar berasal dari pihak yang berhak?</p></div><div class="card"><h3>Fokus kontrol</h3><div class="metric red">Verifikasi</div><p class="sub">Apakah kontrol independen berfungsi atau hanya tercatat sebagai tahapan proses?</p></div><div class="card"><h3>Fokus bukti</h3><div class="metric green">Audit trail</div><p class="sub">Dapatkah fakta transaksi, formulir, peran, dan keterangan saksi dihubungkan?</p></div></div>
  <div class="grid two"><div class="card"><h3>Aturan investigasi</h3><p class="sub">1. Jangan menyimpulkan dari satu bukti. 2. Bedakan fakta, indikator, dan inferensi. 3. Pisahkan kegagalan kontrol dari tanggung jawab pidana individu. 4. Gunakan sumber primer jika tersedia.</p></div><div class="card"><h3>Batas bukti</h3><p class="sub">Aplikasi tidak mengklaim memuat seluruh 117 transaksi. Data transaksi yang tampil merupakan subset terverifikasi dari sumber publik. Elemen antarmuka yang tidak tersedia publik ditandai sebagai rekonstruksi.</p><button class="btn" onclick="advanceStage(2);show('transaksi')">Mulai investigasi</button></div></div>`;
}
function renderTransaksi(){
  const rows=KASUS.transaksi.map(t=>`<tr><td><button class="link-btn" onclick="openTransaction('${t.id}')">${t.id}</button></td><td>${t.tanggal}</td><td>${t.form}</td><td>${t.pengirim}<br><span class="muted">${mask(t.rekeningPengirim)}</span></td><td>${t.penerima}<br><span class="muted">${mask(t.rekeningPenerima)}</span></td><td>${t.bank}</td><td class="amount">${formatAmount(t.jumlah,t.mataUang)}</td><td>${prov(t.provenance)}</td></tr>`).join('');
  $('#transaksiView').innerHTML=`<div class="section-head"><div><h3>Eksplorasi transaksi</h3><p class="sub">Subset transaksi yang dapat diverifikasi dari sumber publik. Klik ID untuk meninjau narasi dan sumber.</p></div><div class="toolbar"><input id="txSearch" placeholder="Cari nama, bank, rekening…"><select id="txCurrency"><option value="">Semua mata uang</option><option>IDR</option><option>USD</option></select></div></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Tanggal</th><th>Form</th><th>Pengirim</th><th>Penerima</th><th>Bank tujuan</th><th>Jumlah</th><th>Provenance</th></tr></thead><tbody id="txBody">${rows}</tbody></table></div><div class="hint" style="margin-top:14px"><b>Pertanyaan investigasi:</b> Pola apa yang terlihat pada penerima, rekening tujuan, narasi, jumlah, dan kemungkinan kebutuhan verifikasi? Pola bukan bukti kesalahan—catat sebagai hipotesis yang harus diuji.</div>`;
  $('#txSearch').oninput=filterTx;$('#txCurrency').onchange=filterTx;
}
function filterTx(){const q=$('#txSearch').value.toLowerCase(),c=$('#txCurrency').value;const filtered=KASUS.transaksi.filter(t=>(!c||t.mataUang===c)&&Object.values(t).join(' ').toLowerCase().includes(q));$('#txBody').innerHTML=filtered.map(t=>`<tr><td><button class="link-btn" onclick="openTransaction('${t.id}')">${t.id}</button></td><td>${t.tanggal}</td><td>${t.form}</td><td>${t.pengirim}</td><td>${t.penerima}</td><td>${t.bank}</td><td class="amount">${formatAmount(t.jumlah,t.mataUang)}</td><td>${prov(t.provenance)}</td></tr>`).join('')}
function openTransaction(id){const t=KASUS.transaksi.find(x=>x.id===id);state.reviewed[id]=true;save();openModal(`<span class="eyebrow">TRANSAKSI ${t.id}</span><h2>${t.pengirim} → ${t.penerima}</h2><div class="grid two"><div class="card"><b>Tanggal</b><p>${t.tanggal}</p><b>Form transfer</b><p>${t.form}</p><b>Bank tujuan</b><p>${t.bank}</p></div><div class="card"><b>Jumlah</b><p>${formatAmount(t.jumlah,t.mataUang)}</p><b>Narasi</b><p>${t.narasi||'Tidak terekspos pada kutipan terverifikasi.'}</p></div></div><div class="warning"><b>Jangan melampaui bukti.</b> Data yang tidak terekspos publik dibiarkan kosong; aplikasi tidak mengisinya dengan asumsi.</div>${sourceBox(t.sumber)}`);updateProgress()}
function renderJaringan(){
  const recipients={};KASUS.transaksi.forEach(t=>{recipients[t.penerima]=(recipients[t.penerima]||0)+1});const top=Object.entries(recipients).sort((a,b)=>b[1]-a[1]);
  $('#jaringanView').innerHTML=`<div class="section-head"><div><h3>Jaringan rekening</h3><p class="sub">Visualisasi hubungan dari subset transaksi terverifikasi—bukan gambaran lengkap seluruh aliran dana perkara.</p></div></div><div class="network"><div class="nodes"><div class="card"><h3>Penerima berulang</h3>${top.map(([n,c])=>`<div class="node"><b>${n}</b><div class="sub">Muncul ${c} kali pada subset saat ini</div></div>`).join('')}</div><div class="hint"><b>Gunakan dengan hati-hati.</b> Frekuensi dalam subset tidak dapat dipakai sebagai estimasi frekuensi dalam seluruh populasi 117 transfer.</div></div><div class="flow">${KASUS.transaksi.slice(0,6).map(t=>`<div class="flow-row"><div class="node"><b>${t.pengirim}</b><small class="muted"><br>${mask(t.rekeningPengirim)}</small></div><div class="flow-arrow">→</div><div class="node"><b>${t.penerima}</b><small class="muted"><br>${t.bank} • ${formatAmount(t.jumlah,t.mataUang)}</small></div></div>`).join('')}</div></div>`;
}
function renderFormulir(){const t=KASUS.transaksi.find(x=>x.form&&x.form!=='—')||KASUS.transaksi[0];$('#formulirView').innerHTML=`<div class="section-head"><div><h3>Form transfer</h3><p class="sub">Rekonstruksi pembelajaran dari bidang yang diketahui; bukan scan formulir asli.</p></div></div><div class="form-preview"><small>REKONSTRUKSI PEMBELAJARAN — BUKAN DOKUMEN ASLI CITIBANK</small><h2>Instruksi Transfer</h2><div class="line"><b>Nomor form:</b> ${t.form}</div><div class="line"><b>Nasabah:</b> ${t.pengirim}</div><div class="line"><b>Rekening sumber:</b> ${mask(t.rekeningPengirim)}</div><div class="line"><b>Penerima:</b> ${t.penerima}</div><div class="line"><b>Rekening tujuan:</b> ${mask(t.rekeningPenerima)}</div><div class="line"><b>Bank:</b> ${t.bank}</div><div class="line"><b>Jumlah:</b> ${formatAmount(t.jumlah,t.mataUang)}</div><div class="line"><b>Berita:</b> ${t.narasi||'—'}</div><div class="line"><b>Tanda tangan nasabah:</b> [tidak direproduksi]</div><div class="line"><b>Verifikasi internal:</b> [tidak direproduksi]</div></div><div class="grid two"><div class="card"><h3>Apa yang harus diuji?</h3><p class="sub">Keaslian instruksi, otorisasi nasabah, kewenangan pemroses, bukti verifikasi, ambang nilai, pemisahan tugas, dan konfirmasi independen.</p></div><div class="card"><h3>Mengapa direkonstruksi?</h3><p class="sub">Sumber publik mengekspos sebagian bidang transaksi, tetapi bukan citra lengkap formulir. Rekonstruksi membantu memahami alur tanpa mengubahnya menjadi bukti historis palsu.</p></div></div>`}
function renderBukti(){const visible=KASUS.artefak.filter(e=>e.tahap<=state.stage);const witnesses=KASUS.saksi.filter(w=>w.tahap<=state.stage);$('#buktiView').innerHTML=`<div class="section-head"><div><h3>Wawancara & ruang bukti</h3><p class="sub">Bukti dilepas bertahap. Meninjau artefak tertentu akan membuka tahap investigasi berikutnya.</p></div><span class="badge primary">Tahap bukti ${state.stage}/4</span></div><h4>Artefak</h4><div class="evidence-grid">${visible.map(e=>`<article class="evidence-card ${state.reviewed[e.id]?'reviewed':''}" onclick="openEvidence('${e.id}')">${prov(e.provenance)}<h4>${e.judul}</h4><p>${e.jenis}</p></article>`).join('')}</div><h4 style="margin-top:24px">Pihak yang dapat diwawancarai</h4><div class="evidence-grid">${witnesses.map(w=>`<article class="evidence-card ${state.reviewed[w.id]?'reviewed':''}" onclick="openWitness('${w.id}')"><span class="prov primary">KETERANGAN BERBASIS SUMBER</span><h4>${w.nama}</h4><p>${w.peran}</p></article>`).join('')}</div>${state.stage<4?`<div class="hint" style="margin-top:16px">Tahap berikutnya terbuka setelah Anda meninjau bukti yang tersedia. Investigasi yang baik tidak menerima semua bukti sekaligus.</div>`:''}`}
function openEvidence(id){const e=KASUS.artefak.find(x=>x.id===id);state.reviewed[id]=true;if(e.tahap>=state.stage&&state.stage<4)state.stage++;save();openModal(`${prov(e.provenance)}<h2>${e.judul}</h2><p>${e.isi}</p>${sourceBox(e.sumber)}`);renderBukti();updateProgress()}
function openWitness(id){const w=KASUS.saksi.find(x=>x.id===id);state.reviewed[id]=true;save();openModal(`<span class="eyebrow">RUANG WAWANCARA</span><h2>${w.nama}</h2><p><b>Peran:</b> ${w.peran}</p><p>${w.ringkas}</p><h3>Pertanyaan yang relevan</h3><ol>${w.pertanyaan.map(q=>`<li>${q}</li>`).join('')}</ol><div class="hint"><b>Catatan metodologis:</b> Ini bukan transkrip wawancara baru. Ringkasan dan pertanyaan disusun untuk pembelajaran berdasarkan peran dan fakta yang terekspos dalam sumber publik.</div>${sourceBox(w.sumber)}`);updateProgress()}
function renderNotebook(){const controls=KASUS.kontrol.map(k=>`<label class="check-item"><input type="checkbox" ${state.clues[k.id]?'checked':''} onchange="state.clues['${k.id}']=this.checked;save();updateProgress()"> <b>${k.id} — ${k.area}</b><div class="sub">${k.fakta}</div></label>`).join('');$('#notebookView').innerHTML=`<div class="section-head"><div><h3>Notebook investigasi</h3><p class="sub">Pilih hanya clue yang dapat Anda pertahankan dengan bukti.</p></div></div><div class="notebook"><div><h3>Kandidat clue</h3><div class="checklist">${controls}</div></div><div class="card"><h3>Catatan profesional</h3><textarea id="notes" placeholder="Fakta → risiko → kontrol yang diharapkan → bukti → keterbatasan → prosedur berikutnya">${state.notes}</textarea><button class="btn" id="saveNotes">Simpan catatan</button></div></div>`;$('#saveNotes').onclick=()=>{state.notes=$('#notes').value;save();updateProgress()}}
function renderKesimpulan(){const options=['Pengendalian transaksi memadai','Terdapat kelemahan desain/pelaksanaan kontrol','Bukti belum cukup untuk menyimpulkan'];$('#kesimpulanView').innerHTML=`<div class="section-head"><div><h3>Kesimpulan profesional</h3><p class="sub">Kesimpulan harus membahas sistem dan kontrol, bukan menentukan kesalahan pidana individu.</p></div></div><div class="decision-options">${options.map(o=>`<button class="decision ${state.decision===o?'selected':''}" onclick="selectDecision('${o.replaceAll("'","\\'")}')"><b>${o}</b><p class="sub">Pilih hanya jika bukti Anda memadai.</p></button>`).join('')}</div><div class="card" style="margin-top:16px"><h3>Dasar kesimpulan</h3><textarea id="rationale" style="width:100%;min-height:220px;background:#0d141d;border:1px solid var(--line);color:var(--text);border-radius:10px;padding:13px" placeholder="Hubungkan fakta transaksi, kontrol, bukti yang mendukung, bukti yang bertentangan, keterbatasan, dan rekomendasi.">${state.rationale}</textarea><button class="btn" id="saveDecision" style="margin-top:10px">Simpan kesimpulan</button></div><div class="warning" style="margin-top:16px"><b>Nuansa hukum wajib:</b> aplikasi tidak boleh menyamakan adanya masalah proses/kontrol dengan kesalahan pidana pihak tertentu. Putusan PK 99 PK/Pid.Sus/2016 harus dipertimbangkan secara akurat.</div>`;$('#saveDecision').onclick=()=>{state.rationale=$('#rationale').value;save();updateProgress()}}
function selectDecision(v){state.decision=v;save();renderKesimpulan();updateProgress()}
function advanceStage(n){if(state.stage<n){state.stage=n;save()}}
function updateProgress(){const reviewed=Object.keys(state.reviewed).filter(k=>state.reviewed[k]).length,clues=Object.values(state.clues).filter(Boolean).length;let score=Math.min(100,Math.round((reviewed/8)*45+(clues/4)*25+(state.notes.trim()?15:0)+(state.decision&&state.rationale.trim()?15:0)));$('#progressText').textContent=score+'%';$('#progressBar').style.width=score+'%';$('#evidenceCount').textContent=`${reviewed} bukti ditinjau`}
function mask(v){if(!v)return '—';const s=String(v);return s.length<7?s:s.slice(0,3)+'••••'+s.slice(-3)}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false')}
function closeModal(){$('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true')}
init();
